# Generated by Django 3.2 on 2021-04-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('days', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.CharField(max_length=50)),
                ('trip_diff', models.CharField(max_length=50)),
                ('trip_style', models.CharField(max_length=50)),
                ('transport', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('accommodation', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'UnPublish'), (1, 'Publish')], default=0)),
            ],
        ),
    ]
