# Generated by Django 3.2 on 2021-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(blank=True, unique=True)),
                ('ephone', models.IntegerField(blank=True, unique=True)),
                ('package', models.CharField(max_length=20)),
                ('pickupdetails', models.TextField(max_length=30)),
            ],
        ),
    ]
