# Generated by Django 3.2 on 2021-05-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, null=True)),
                ('lname', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('package', models.CharField(max_length=50, null=True)),
                ('review_title', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reviewdetails', models.TextField(max_length=900, null=True)),
            ],
        ),
    ]
