# Generated by Django 3.2 on 2021-05-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_boby_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='guide',
            name='skills',
            field=models.CharField(max_length=250),
        ),
    ]
